### PR TITLE
[PK-224] Ошибка генерации курсоров из пакета по умолчанию

### PR DESCRIPTION
**Pull request by packpaul**
BF

## Overview

Unit test data fixed

---

### Checklist

- [ ] Change is covered by automated tests.
- [x] JavaDoc is provided for all new/changed public APIs.
- [x] User Guide is updated.
- [x] CI builds pass.

### CODE REVIEW

**Review by inponomarev — CHANGES_REQUESTED** [review]
It's not the first time I'm coming across this misunderstanding, but: 'Change is covered by tests' doesn't mean it's ok **not** to add new tests if code coverage remains full for the changed code. 

I would expect the following: 

* make `CursorGenerator#calcSourcePackage` method package private
* write a couple of unit tests for this method, one of which should reproduce the `StringIndexOutOfBoundsException` from the Jira issue
* if it's hard to provide the real `GrainElement` as an argument, the tests can be mock-based

**Comment by packpaul** [comment]
> It's not the first time I'm coming across this misunderstanding, but: 'Change is covered by tests' doesn't mean it's ok **not** to add new tests if code coverage remains full for the changed code.
> 
> I would expect the following:
> 
> * make `CursorGenerator#calcSourcePackage` method package private
> * write a couple of unit tests for this method, one of which should reproduce the `StringIndexOutOfBoundsException` from the Jira issue
> * if it's hard to provide the real `GrainElement` as an argument, the tests can be mock-based

**Comment by packpaul** [comment]
Tests for CursorGenerator#calcSourcePackag added.

**Review by inponomarev — APPROVED** [review]

**Comment by inponomarev** [comment]
👍 OK to merge!

**Pull request merged**
